export const LOAD_COMMENT="LOAD_COMMENT";
export const LOAD_COMMENT_SUCCESS="LOAD_COMMENT_SUCCESS";
export const LOAD_COMMENT_ERROR="LOAD_COMMENT_ERROR";
export const ADD_BOOKS="ADD_BOOKS";
export const DELETE_BOOKS="DELETE_BOOKS";
export const DELETE_ALL_BOOKS="DELETE_ALL_BOOKS";
export const SEARCH_BOOKS="SEARCH_BOOKS";
export const SEARCH_BOOKS_SUCCESS="SEARCH_BOOKS_SUCCESS";
export const SEARCH_BOOKS_ERROR="SEARCH_BOOKS_ERROR";

